server:
  port: 8082

logging:
  config: classpath:logback.xml
  level:  
    org: 
      springframework: 
        web: INFO,ERROR

spring:
  application: 
    name: spring-eureka-client
    
eureka: 
  client: 
    service-url: 
      defaultZone: http://116.62.56.23:1111/eureka/
      